import type {Metadata} from "next";
import "./globals.css";
import {Theme} from '@radix-ui/themes';
import React from "react";
import Footer from "@/components/footer";
// @ts-ignore
// import {Heti} from "heti/js/heti-addon"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    // const heti = new Heti('.heti');
    // heti.autoSpacing(); // 自动进行中西文混排美化和标点挤压
    return (
        <html lang="en">
        <body>
        <Theme>
            <div className={"flex justify-center bg-[#f7f7f7]"}>
                {children}
            </div>
            <Footer/>
        </Theme>
        </body>
        </html>
    );
}
